name: Run Node.js Script

on:
  push:
    branches:
      - main  # Mude para o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      CI_COMMIT_AUTHOR: Continuous Integration

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Mude para a versão do Node.js que você está usando

    - name: Install dependencies
      run: pnpm install  # Ou use yarn se preferir

    - name: Run Node.js script
      run: node dist/main.js # Substitua 'seu-arquivo-node.js' pelo nome do seu arquivo Node.js
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated Commit"
        branch: blog